export const KPI_COLORS = {
  heating:   '#f04d5b',
  dhw:       '#f58345',
  cooling:   '#3fc0c2',
  electricity:'#7ec78f',
  solar:     '#ffd11d',
  pvt:       '#ab8f1e',
  sc:        '#e8a800',
  geothermal:'#7b8c5a',
  sewage:    '#94a3b8',
  dh:        '#e87070',
  ng:        '#f58345',
  grid:      '#5c6bc0',
  capex:     '#eab308',
  opex:      '#3b82f6',
  ghg_op:    '#f04d5b',
  ghg_emb:   '#94a3b8',
  outdoor:   '#94a3b8',

  // Solar orientation shades
  roofs_top:     '#ffd11d',
  walls_south:   '#f97316',
  walls_east:    '#fb923c',
  walls_west:    '#fdba74',
  walls_north:   '#92400e',
  windows_south: '#fef08a',
  windows_east:  '#fef9c3',
  windows_west:  '#fefce8',
  windows_north: '#d4d4d4',

  // Thermal balance
  I_sol:             '#ffd11d',
  Q_gain_sen_peop:   '#86efac',
  Q_gain_sen_light:  '#6ee7b7',
  Q_gain_sen_app:    '#a16207',
  Q_gain_sen_wall:   '#f97316',
  Q_loss_sen_ref:    '#3fc0c2',
  I_rad:             '#cbd5e1',
} as const;

export function removeZeroSeries<T extends { data: number[] }>(series: T[]): T[] {
  return series.filter((s) => s.data.reduce((a, b) => a + Math.abs(b), 0) > 1e-4);
}

export const FIELD_LABELS: Record<string, string> = {
  Qhs_sys_MWhyr:  'Space Heating',
  Qww_sys_MWhyr:  'Domestic Hot Water',
  Qcs_sys_MWhyr:  'Space Cooling',
  E_sys_MWhyr:    'Electricity',
  QH_sys_MWhyr:   'Total Heating',
  QC_sys_MWhyr:   'Total Cooling',
  E_sys0_kW:      'Peak Electricity',
  Qhs_sys0_kW:    'Peak Heating',
  Qcs_sys0_kW:    'Peak Cooling',
  Qhs_sys_kWh:    'Space Heating',
  Qww_sys_kWh:    'Domestic Hot Water',
  Qcs_sys_kWh:    'Space Cooling',
  E_sys_kWh:      'Electricity',
  QH_sys_kWh:     'Total Heating',
  QC_sys_kWh:     'Total Cooling',
  theta_op_avg_C: 'Avg. Operative Temp (°C)',
  I_sol_kWh:      'Solar Gains',
  Q_gain_sen_peop_kWh:  'People Gains',
  Q_gain_sen_light_kWh: 'Lighting Gains',
  Q_gain_sen_app_kWh:   'Appliance Gains',
  Q_gain_sen_wall_kWh:  'Wall Gains',
  Q_loss_sen_ref_kWh:   'Ref. Heat Loss',
  I_rad_kWh:            'Radiation Loss',
  roofs_top:     'Roofs (Top)',
  walls_south:   'Walls South',
  walls_east:    'Walls East',
  walls_west:    'Walls West',
  walls_north:   'Walls North',
  windows_south: 'Windows South',
  windows_east:  'Windows East',
  windows_west:  'Windows West',
  windows_north: 'Windows North',
};
